In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
start =pd.read_csv('dataset.csv')
start=start.iloc[:,1:]

In [3]:
start

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                              -1              1                   1   
1                               1              1                   1   
2                               1              0                   1   
3                               1              0                   1   
4                               1              0                  -1   
...                           ...            ...                 ...   
11050                           1             -1                   1   
11051                          -1              1                   1   
11052                           1             -1                   1   
11053                          -1             -1                   1   
11054                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  \
0                     -1              -1                           -1   
1                      0               1                           -1   
2                     -1              -1                           -1   
3                     -1              -1                            1   
4                      1               1                           -1   
...                  ...             ...                          ...   
11050                  1               1                           -1   
11051                  1              -1                           -1   
11052                  1              -1                           -1   
11053                 -1              -1                            1   
11054                 -1              -1                            1   

       Favicon  ...  popUpWidnow  Iframe  age_of_domain  DNSRecord  \
0            1  ...            1       1             -1         -1   
1            1  ...            1       1             -1         -1   
2            1  ...            1       1              1         -1   
3            1  ...            1       1             -1         -1   
4            1  ...           -1       1             -1         -1   
...        ...  ...          ...     ...            ...        ...   
11050       -1  ...           -1      -1              1          1   
11051       -1  ...           -1       1              1          1   
11052        1  ...            1       1              1          1   
11053       -1  ...           -1       1              1          1   
11054        1  ...            1       1             -1          1   

       web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0               -1         -1             1                       1   
1                0         -1             1                       1   
2                1         -1             1                       0   
3                1         -1             1                      -1   
4                0         -1             1                       1   
...            ...        ...           ...                     ...   
11050           -1         -1             1                       1   
11051            1          1          

In [4]:
start.isnull().any()

having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
Page_Rank                      False
G

In [14]:
start=start.drop(['Shortining_Service','Prefix_Suffix','Favicon','SFH','on_mouseover','Iframe','RightClick'],axis=1)

In [22]:
x=start.iloc[:,0:22].values
y=start.iloc[:,23:].values
x

array([[-1,  1,  1, ..., -1,  1,  1],
       [ 1,  1,  1, ..., -1,  1,  1],
       [ 1,  0,  1, ..., -1,  1,  0],
       ...,
       [ 1, -1,  1, ..., -1,  1,  0],
       [-1, -1,  1, ..., -1,  1,  1],
       [-1, -1,  1, ..., -1, -1,  1]], dtype=int64)

In [23]:
y

array([[-1],
       [-1],
       [-1],
       ...,
       [-1],
       [-1],
       [-1]], dtype=int64)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [26]:
x_train

array([[ 1, -1,  1, ...,  1,  1,  1],
       [ 1,  1, -1, ...,  1,  1,  0],
       [-1, -1,  1, ..., -1,  1,  1],
       ...,
       [-1,  1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ..., -1,  1,  1],
       [ 1, -1,  1, ..., -1,  1,  1]], dtype=int64)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
lr=LogisticRegression()

In [29]:
lr.fit(x_train,y_train)

C:\Users\91638\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [30]:
y_pred=lr.predict(x_test)

In [31]:
y_test

array([[-1],
       [-1],
       [-1],
       ...,
       [ 1],
       [ 1],
       [ 1]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9118046132971506

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import neighbors

In [34]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)

<ipython-input-34-f567737eba31>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  clf.fit(x_train,y_train)


KNeighborsClassifier()

In [35]:
y_pred=clf.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9353233830845771

In [38]:
print(clf.predict([[1,-1,1,1,-1,1,1,1,1,-1,1,1,1,1,-1,1,1,1,-1,1,1,1]]))

[1]
